polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

servisiux/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='servisiux/index'),
    path('stats/', views.stats, name='stats'),
    path('cars/', views.cars, name='cars'),
    path('cars/<int:car_id>', views.car, name='car'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('search/', views.search, name='servisiux/search'),
    path('myorders/', views.UserOrdersListView.as_view(), name='my-orders'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='servisiux/profile'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('userorders/', views.UserOrders.as_view(), name='user-orders'),
    path('userorders/<int:pk>', views.UserOrdersDetail.as_view(), name='user-order'),
    path('userorders/new', views.UserOrderCreateView.as_view(), name='user-orders-new'),
    path('userorders/<int:pk>/update', views.UserOrderUpdateView.as_view(), name='user-order-update'),
    path('userorders/<int:pk>/delete', views.UserOrderDeleteView.as_view(), name='user-order-delete'),
    path('userorders/<int:pk>/newrow', views.OrderRowCreateView.as_view(), name='row-new'),
]

startdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('servisiux/', include('servisiux.urls')),
    path('polls/', include('polls.urls')),
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +  
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
    

servisiux/models.py
from datetime import date, datetime
import pytz
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _
from django.shortcuts import reverse

utc=pytz.UTC

# Create your models here.

class CarModel(models.Model):
  make = models.CharField('Make', max_length=200)
  model = models.CharField('Model', max_length=200)

  def __str__(self):
      return (f"{self.make} {self.model}")

  class Meta:
      verbose_name = 'Model'
      verbose_name_plural = 'Models'        


class Car(models.Model):
  plate = models.CharField('License plate', max_length=200)
  model_id = models.ForeignKey('Carmodel', on_delete=models.SET_NULL, null=True, related_name="carmodel")
  vin = models.CharField('VIN number', max_length=200)
  own_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
#   owner = models.CharField('Owner name, surname', max_length=200)
  cover = models.ImageField('Carpic', upload_to='service/cars', null=True)
  description = HTMLField()

  @property
  def car_suma(self):
      orders = Order.objects.filter(car_instance_id=self.id)
      recipe = 0
      for row in orders:
          recipe += row.suma
      return recipe

  def __str__(self):
      return f'{self.plate}'

  class Meta:
      verbose_name = 'Car'
      verbose_name_plural = 'Cars'

class Order(models.Model):
  date = models.DateField('Date', null=True, blank=True)
  car_instance_id = models.ForeignKey('Car', on_delete=models.SET_NULL, null=True, related_name='carorder')
  user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
  due_date = models.DateField('Due date', null=True, blank=True)

#   link = models.CharField('link', max_length=50, default='Open order')
  def get_absolute_url(self):
    return reverse('user-order', args=[str(self.id)])

  @property
  def suma(self):
      order_rows = OrderRow.objects.filter(order_id=self.id)
      recipe = 0
      for row in order_rows:
          recipe += row.quantity * row.service_id.price
      return recipe

  @property
  def is_overdue(self):
    if self.due_date and date.today() > self.due_date:
        return True
    return False

  def __str__(self):
      return f'{self.car_instance_id}'

  class Meta:
      verbose_name = 'Order'
      verbose_name_plural = 'Orders'
  
  def save(self, *args, **kwargs):
      self.link = f'Open order'
      super().save(*args, **kwargs)

  ORDER_STATUS = (
    ('e', 'Entered'),
    ('w', 'Waiting'),
    ('p', 'In progress'),
    ('c', 'Completed'),
    )

  status = models.CharField(
    max_length=1,
    choices=ORDER_STATUS,
    blank=True,
    default='e',
    help_text='Status',
    )

class OrderRow(models.Model):
  service_id = models.ForeignKey('Service', on_delete=models.SET_NULL, null=True)
  order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
  quantity = models.IntegerField('Quantity')

  def __str__(self):
      return f'{self.order_id}, {self.quantity}'

  class Meta:
      verbose_name = 'Row'
      verbose_name_plural = 'Rows'  
      unique_together = ('service_id', 'order')


class Service(models.Model):
  service = models.CharField('Service', max_length=200)
  price = models.FloatField('Price', max_length=200)

  def __str__(self):
      return f'{self.service}'

  class Meta:
      verbose_name = 'Service'
      verbose_name_plural = 'Services'

class OrderReview(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.picture.path)        

servisiux/forms.py
from .models import OrderReview, OrderRow, Profile, Order
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

class OrderReviewForm(forms.ModelForm):
    class Meta:
        model = OrderReview
        fields = ('content', 'order', 'reviewer',)
        widgets = {'order': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture']


class DateInput(forms.DateInput):
    input_type = 'date'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = fields = '__all__'
        fields = ['car_instance_id', 'due_date']
        widgets = {
            'due_date': DateInput(), 'user': forms.HiddenInput(), 'date': forms.HiddenInput()}


class RowForm(forms.ModelForm):
    class Meta:
        model = OrderRow
        fields = ['service_id', 'quantity']
        widgets = {
            'order': forms.HiddenInput()}
           

servisiux/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from .models import CarModel, Car, Order, OrderRow, Service
from django.views.generic import (
                                ListView,
                                DetailView,
                                DeleteView,
                                CreateView,
                                UpdateView,
                                )
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import OrderForm, OrderReviewForm, UserUpdateForm, ProfileUpdateForm, RowForm
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from datetime import date

# Create your views here.
def index(request):
    return render(request, 'servisiux/index.html')

def stats(request):
    qty_services = Service.objects.all().count()
    qty_orders = Order.objects.all().count()
    qty_cars = Car.objects.all().count()
    qty_models = CarModel.objects.all().count()

    context = {
        'qty_serv': qty_services,
        'qty_orders': qty_orders,
        'qty_cars': qty_cars,
        'qty_models': qty_models,
    }
    return render(request, 'servisiux/stats.html', context=context)

def cars(request):
    # cars = Car.objects.all()
    paginator = Paginator(Car.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_cars = paginator.get_page(page_number)
    context = {
        'cars': paged_cars
    }
    # print(cars)
    return render(request, 'servisiux/cars.html', context=context)

def car(request, car_id):
    single_car = get_object_or_404(Car, pk = car_id)
    # car_orders = Order.objects.get()
    return render(request, 'servisiux/car.html', {'car': single_car})

class OrderListView(ListView):
    model = Order
    paginate_by = 5
    template_name = 'servisiux/order_list.html'

class OrderDetailView(FormMixin, DetailView):
    model = Order
    template_name = 'servisiux/order_detail.html'
    form_class = OrderReviewForm

    class Meta:
        ordering = ['title']

    def get_success_url(self):
        return reverse('order-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
       context = super(OrderDetailView, self).get_context_data(**kwargs)
       context['form'] = OrderReviewForm(initial={'order': self.object})
       return context   

    def post(self, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)

def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės 
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Car.objects.filter(Q(model_id__make__icontains=query) | Q(owner__icontains=query))
    return render(request, 'servisiux/search.html', {'cars': search_results, 'query': query})

class UserOrdersListView(LoginRequiredMixin, ListView):
    model = Order
    template_name ='servisiux/user_orders.html'
    paginate_by = 10
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('due_date')

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'registration/register.html')

@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profile updated")
            return redirect('servisiux/profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }    
    return render(request, 'servisiux/profile.html', context)

class UserOrders(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'servisiux/my_orders.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('due_date')

class UserOrdersDetail(LoginRequiredMixin, DetailView, FormMixin):
    model = Order
    template_name = 'servisiux/my_order.html'

    form_class = OrderReviewForm


    class Meta:
        ordering = ['title']

    def get_success_url(self):
        return reverse('user-order', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
       context = super(UserOrdersDetail, self).get_context_data(**kwargs)
       context['form'] = OrderReviewForm(initial={'order': self.object})
       return context   

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(UserOrdersDetail, self).form_valid(form)


class UserOrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm

    success_url = "/servisiux/userorders/"
    template_name = 'servisiux/my_order_new.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.date = date.today()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].fields['car_instance_id'].queryset = Car.objects.filter(own_id=self.request.user)
        return context


class UserOrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Order
    form_class = OrderForm

    success_url = "/servisiux/userorders/"
    template_name = 'servisiux/my_order_new.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.date = date.today()
        return super().form_valid(form)

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.user


class UserOrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Order
    success_url = "/servisiux/userorders/"
    template_name = 'servisiux/my_order_delete.html'

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.user


class OrderRowCreateView(LoginRequiredMixin, CreateView):
    model = OrderRow
    form_class = RowForm
    success_url = "/servisiux/userorders/"
    template_name = 'servisiux/order_row_new.html'

    # def get_success_url(order):
    #     return reverse('user-order', kwargs={'pk': order.id})


    def form_valid(self, form):
        # form.instance.orderrow = self.request.orderrow
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        order = self.object
        context = super().get_context_data(**kwargs)
        # context['form'].fields['car_instance_id'].queryset = Car.objects.filter(own_id=self.request.user)
        return context

servisiux/templates/servisiux/car.html
{% extends "servisiux/base.html" %}
{% block title %}<title>Service | Car</title>{% endblock %}
{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5">{{car.model_id}}</h2>
    <img src="{{ car.cover.url }}" class="img-fluid">
    <div class="subheading mb-3">Driver: {{ car.own_id_id }} / License plate: {{ car.plate }}</div>
    <div class="subheading mb-3">VIN: {{ car.vin }}</div>
    <div>{{ car.description | safe }} </div>
    <ul>
      {% for order in car.carorder.all %}
        <li><a href="{% url 'order-detail' order.id %}">{{ order.date }}</a> {{ order.get_status_display}}</li>
      {% endfor %}
      <li>{{ car.car_suma }}</li>
  </ul>
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/cars.html
{% extends "servisiux/base.html" %}

{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5">All cars serviced</h2>
    <div class="subheading mb-3">Our stats</div>
    {% if cars %}
    <ul class="fa-ul mb-0">
      {% for car in cars %}
        <li class="text-center">
          <img src="{{ car.cover.url }}" class="w-50 img-thumbnail rounded mx-auto d-block">
          <!-- <span class="fa-li"><i class="fas fa-check"></i></span> -->
            <a class="text-center" href="{{ car.id }}">{{ car.model_id }}</a>
          <hr>
        </li>
      {% endfor %}
    </ul>
    <div>
      <nav aria-label="...">
          {% if cars.has_other_pages %}
              <ul class="pagination pagination-sm justify-content-center">
                  {% for i in cars.paginator.page_range %}
                      {% if cars.number == i %}
                          <li class="page-item active">
                            <a class="page-link" href">{{ i }}</a>
                          </li>
                      {% else %}
                          <li class="page-item">
                              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                          </li>
                      {% endif %}
                  {% endfor %}
              </ul>
          {% endif %}
      </nav>
    </div>
    {% else %}
      <p>No service provided.</p>
    {% endif %}
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/index.html
{% extends "servisiux/base.html" %}
{% load i18n %}
{% block content %}
<section class="resume-section" id="about">
  <div class="resume-section-content">
    <h1 class="mb-0">
      {% trans "Old Cars" %}
        <span class="text-primary">{% trans "Service" %}</span>
    </h1>
    <div class="subheading mb-5">
      Caring service for nice cars
    </div>
    <div class="subheading mb-5">
      3542 Berry Street · Cheyenne Wells, CO 80810 · (317) 585-8468 ·
      <a href="mailto:name@email.com">name@email.com</a>
    </div>
    <p class="lead mb-5">We know You love your car. We do too. Our passion are servicing old cars and make them beautifull.</p>
    <div class="social-icons">
        <a class="social-icon" href="#!"><i class="fab fa-linkedin-in"></i></a>
        <a class="social-icon" href="#!"><i class="fab fa-github"></i></a>
        <a class="social-icon" href="#!"><i class="fab fa-twitter"></i></a>
        <a class="social-icon" href="#!"><i class="fab fa-facebook-f"></i></a>
    </div>
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/my_order.html
{% extends "servisiux/base.html" %}

{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5"><a href="{% url 'car' order.car_instance_id.id %}">{{order.car_instance_id.model_id}}</a></h2>
    <div class="subheading mb-3">{{ order.car_instance_id }}</div>
    <div class="subheading mb-3">Order date: {{ order.date }}</div>
    <div class="subheading mb-3">Due date: {{ order.due_date }}</div>
    <div class="subheading mb-3">Status: {{ order.get_status_display }}</div>
  </div>
  <div class="resume-section-content">
    <a class="btn btn-primary" href="{{ order.id }}/newrow" role="button">New service</a>
    {% if order.orderrow_set.all %}
    <ul>
      {% for row in order.orderrow_set.all %}
      <li>
          {{ row.quantity }} {{ row.service_id.service }}, {{ row.service_id.price }}
      </li>
      {% endfor %}
      <li>Total €: {{ order.suma }}</li>
    </ul>
    {% endif %}
  </div>
  <div class="resume-section-content">
  </br>
  <h4>Reviews:</h4>
  {% if order.orderreview_set.all %}
    {% for review in order.orderreview_set.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>You have no reviews.</p>
  {% endif %}
  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Write your review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Post">
    </form>
  </div>
  {% endif %}
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/my_order_delete.html
{% extends "servisiux/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Delete order</legend>
          <h2>Do you really want to delete order (irreversible) {{ object.pk }}?</h2>
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-danger" type="submit">Yes</button>
          <a class="btn btn-outline-secondary" href="{% url 'user-order' order.id %}">Cancel</a>
      </div>
  </form>
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/my_order_new.html
{% extends "servisiux/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">New order</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Submit</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/my_orders.html
{% extends "servisiux/base.html" %}

{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5">{{user}} orders</h2>
    {% if orders %}
    <img class="rounded-circle img-thumbnail" src="{{user.profile.picture.url}}">
    <ul class="fa-ul mb-0 mt-4">
      {% for order in orders %}
        <li class="{% if order.is_overdue %}text-danger{% endif %} mt-4">
          <img class="w-25 img-thumbnail rounded d-block" src="{{order.car_instance_id.cover.url}}">
          <span class="fa-li"><i class="fas fa-check"></i></span>
            Status info: {{ order.date }}, {{ order.car_instance_id }} <a href="{% url 'order-detail' order.id %}">{{ order.get_status_display}}</a>
            <br/>
            <a class="btn btn-primary" href="{{ order.pk }}" role="button">View</a>
            <a class="btn btn-secondary" href="{% url 'user-order-update' order.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'user-order-delete' order.id %}">Delete</a>
        </li>
      {% endfor %}
    </ul>
    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">back</a>
          {% endif %}
  
          <span class="current">
              {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">forward</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>      
    {% else %}
      <p>No orders in system.</p>
    {% endif %}
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/order_detail.html
{% extends "servisiux/base.html" %}

{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5"><a href="{% url 'car' order.car_instance_id.id %}">{{order.car_instance_id.model_id}}</a></h2>
    <div class="subheading mb-3">{{ order.car_instance_id }}</div>
    <div class="subheading mb-3">Order date: {{ order.date }}</div>
    <div class="subheading mb-3">Status: {{ order.get_status_display }}</div>
  </div>
  <div class="resume-section-content">
    <ul>
      {% for row in order.orderrow_set.all %}
      <li>
          {{ row.quantity }} {{ row.service_id.service }}, {{ row.service_id.price }}
      </li>
      {% endfor %}
      <li>Total €: {{ order.suma }}</li>
    </ul>
  </div>
  <div class="resume-section-content">
  </br>
  <h4>Reviews:</h4>
  {% if order.orderreview_set.all %}
    {% for review in order.orderreview_set.all %}
      <hr>
      <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>You have no reviews.</p>
  {% endif %}
  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Write your review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Post">
    </form>
  </div>
  {% endif %}
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/order_list.html
{% extends "servisiux/base.html" %}

{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <h2 class="mb-5">All orders</h2>
    <div class="subheading mb-3">Our stats</div>
    {% if order_list %}
    <ul class="fa-ul mb-0">
      {% for order in order_list %}
        <li>
          <span class="fa-li"><i class="fas fa-check"></i></span>
            Status info: {{ order.date }}, {{ order.car_instance_id }} <a href="{{ order.id }}">{{ order.get_status_display}}</a> 
        </li>
      {% endfor %}
    </ul>
    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">back</a>
          {% endif %}
  
          <span class="current">
              {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">forward</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>      
    {% else %}
      <p>No orders in system.</p>
    {% endif %}
  </div>
</section>
{% endblock %}

servisiux/templates/servisiux/order_row_new.html
{% extends "servisiux/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<section class="resume-section" id="skills">
  <div class="resume-section-content">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">New service</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Submit</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}